name: "Publish Package"
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install and build packages
        run: |
          pnpm install --frozen-lockfile
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          pnpm version ${{ github.ref_name }} --git-tag-version false
          pnpm build

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          packages=(client server shared)
          for package in "${packages[@]}"; do
            if [ -f "./lib/$package/package.json" ]; then
              pnpm publish --no-git-checks --access public "./lib/$package"
            fi
          done

      - name: Push new commits
        run: |
          git add .
          git commit -am '${{ github.ref_name }}'
          git push

